"""
Shared constants and vocabulary for the AECCS pipeline and extension.

This module is the single source of truth for Python-owned constants that are
also needed by the packaged browser extension. The extension consumes a
generated JS payload built from these definitions.
"""

from __future__ import annotations

import re
import unicodedata


def _dedupe_preserve_order(values: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def normalize_match_text(value: str | None) -> str:
    text = str(value or "").strip()
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    return " ".join(text.lower().split())


CONSENT_ACTION_VOCABULARY: dict[str, dict[str, list[str]]] = {
    "accept": {
        "exact": [
            "Accept",
            "Accept All",
            "Accept Cookies",
            "Allow All",
            "Allow All Cookies",
            "Agree",
            "I Agree",
            "Akzeptieren",
            "Alle akzeptieren",
            "Zustimmen",
            "Einverstanden",
            "Accepter",
            "Tout accepter",
            "J'accepte",
            "Accepteren",
            "Alle accepteren",
            "Aceptar",
            "Aceptar todo",
            "Aceptar todas",
            "Accetta",
            "Accetta tutto",
            "Accetta tutti",
            "Aceitar",
            "Aceitar tudo",
            "Aceitar todos",
            "Akceptuj",
            "Akceptuj wszystko",
            "Zaakceptuj",
            "Zaakceptuj wszystko",
            "Accepta",
            "Acceptă",
            "Accept tot",
            "Accept totul",
            "Prijmout",
            "Přijmout",
            "Prijmout vse",
            "Přijmout vše",
            "Acceptera",
            "Acceptera alla",
            "Godkänn alla",
            "Godkjenn alle",
            "Accepter alle",
            "Godta",
            "Godta alle",
            "Aksepter",
            "Aksepter alle",
            "Hyvaksy",
            "Hyväksy",
            "Hyvaksy kaikki",
            "Hyväksy kaikki",
            "Apodechomai",
            "Αποδέχομαι",
            "Apodochi",
            "Αποδοχή",
            "Apodochi olon",
            "Αποδοχή όλων",
            "Elfogad",
            "Elfogadom",
            "Mindent elfogad",
            "Osszes elfogadasa",
            "Összes elfogadása",
            "Prijat",
            "Prijať",
            "Prijat vsetko",
            "Prijať všetko",
            "Sprejmi",
            "Sprejmi vse",
            "Prihvati",
            "Prihvati sve",
            "Priemam",
            "Приемам",
            "Priemam vsichki",
            "Приемам всички",
            "Priimti",
            "Priimti visus",
            "Pienemt",
            "Pieņemt",
            "Pienemt visu",
            "Pieņemt visu",
            "Noustu",
            "Nõustu",
            "Noustun",
            "Nõustun",
            "Samthykkja",
            "Samþykkja",
            "Samthykkja allt",
            "Samþykkja allt",
            "Glac",
            "Glac le gach",
            "Accetta",
            "Aċċetta",
            "Accetta kollox",
            "Aċċetta kollox",
            "Kabul Et",
            "Tumunu Kabul Et",
            "Tümünü Kabul Et",
            "Izin Ver",
            "İzin Ver",
        ],
        "contains": [
            "accept all cookies",
            "accept and continue",
            "allow all cookies",
            "agree and continue",
            "alle cookies akzeptieren",
            "accepter tout",
            "alle cookies accepteren",
            "aceitar cookies",
            "sunt de acord",
            "souhlasim",
            "souhlasím",
            "zgadzam sie",
            "zgadzam się",
            "leyfa allt",
            "permitir tudo",
            "salli kaikki",
            "piekritu",
            "piekrītu",
            "sutinku",
            "slazem se",
            "slažem se",
            "naqbel",
        ],
    },
    "reject": {
        "exact": [
            "Reject",
            "Reject All",
            "Decline",
            "Decline All",
            "Deny",
            "Deny All",
            "Refuse All",
            "Continue without accepting",
            "Essential cookies only",
            "Necessary cookies only",
            "Only essential cookies",
            "Only necessary cookies",
            "Use essential cookies only",
            "Use necessary cookies only",
            "Ablehnen",
            "Alle ablehnen",
            "Nur notwendige Cookies",
            "Nur essentielle Cookies",
            "Nur erforderliche Cookies",
            "Ohne Akzeptieren fortfahren",
            "Refuser",
            "Tout refuser",
            "Refuser tout",
            "Continuer sans accepter",
            "Cookies essentiels uniquement",
            "Cookies necessaires uniquement",
            "Accepter uniquement les cookies necessaires",
            "Weigeren",
            "Alle weigeren",
            "Alleen noodzakelijke cookies",
            "Alleen essentiele cookies",
            "Doorgaan zonder te accepteren",
            "Rechazar",
            "Rechazar todo",
            "Rechazar todas",
            "Solo cookies necesarias",
            "Solo cookies esenciales",
            "Continuar sin aceptar",
            "Rifiuta",
            "Rifiuta tutto",
            "Rifiuta tutti",
            "Solo cookie necessari",
            "Solo cookie essenziali",
            "Continua senza accettare",
            "Rejeitar",
            "Rejeitar tudo",
            "Recusar",
            "Recusar tudo",
            "Apenas cookies necessarios",
            "Apenas cookies essenciais",
            "Continuar sem aceitar",
            "Odrzuc",
            "Odrzuć",
            "Odrzuc wszystko",
            "Odrzuć wszystko",
            "Odmow",
            "Odmów",
            "Tylko niezbedne pliki cookie",
            "Tylko niezbędne pliki cookie",
            "Kontynuuj bez akceptacji",
            "Respinge",
            "Respinge tot",
            "Refuz",
            "Doar cookie-uri necesare",
            "Doar cookie-uri esentiale",
            "Doar cookie-uri esențiale",
            "Continua fara a accepta",
            "Continuă fără a accepta",
            "Odmitnout",
            "Odmítnout",
            "Odmitnout vse",
            "Odmítnout vše",
            "Pouze nezbytne cookies",
            "Pouze nezbytné cookies",
            "Pouze nutne cookies",
            "Pouze nutné cookies",
            "Pokracovat bez prijeti",
            "Pokračovat bez přijetí",
            "Avvisa",
            "Avvisa alla",
            "Endast nodvandiga cookies",
            "Endast nödvändiga cookies",
            "Fortsatt utan att acceptera",
            "Fortsätt utan att acceptera",
            "Afvis",
            "Afvis alle",
            "Kun nodvendige cookies",
            "Kun nødvendige cookies",
            "Fortsaet uden at acceptere",
            "Fortsæt uden at acceptere",
            "Avvis",
            "Avvis alle",
            "Bare nodvendige cookies",
            "Bare nødvendige cookies",
            "Fortsett uten a akseptere",
            "Fortsett uten å akseptere",
            "Hylkaa",
            "Hylkää",
            "Hylkaa kaikki",
            "Hylkää kaikki",
            "Vain valttamattomat evasteet",
            "Vain välttämättömät evästeet",
            "Jatka hyvaksymatta",
            "Jatka hyväksymättä",
            "Aporripsi",
            "Απόρριψη",
            "Aporripsi olon",
            "Απόρριψη όλων",
            "Mono aparaitita cookies",
            "Μόνο απαραίτητα cookies",
            "Synecheia choris apodochi",
            "Συνέχεια χωρίς αποδοχή",
            "Elutasit",
            "Elutasít",
            "Osszes elutasitasa",
            "Összes elutasítása",
            "Csak a szukseges sütik",
            "Csak a szükséges sütik",
            "Folytatas elfogadas nelkul",
            "Folytatás elfogadás nélkül",
            "Odmietnut",
            "Odmietnuť",
            "Odmietnut vsetko",
            "Odmietnuť všetko",
            "Iba nevyhnutne cookies",
            "Iba nevyhnutné cookies",
            "Pokracovat bez prijatia",
            "Pokračovať bez prijatia",
            "Zavrni",
            "Zavrni vse",
            "Samo nujni piskotki",
            "Samo nujni piškotki",
            "Nadaljuj brez sprejema",
            "Odbij",
            "Odbij sve",
            "Samo nuzni kolacici",
            "Samo nužni kolačići",
            "Nastavi bez prihvacanja",
            "Nastavi bez prihvaćanja",
            "Othvarlyam",
            "Отхвърлям",
            "Othvarlyam vsichki",
            "Отхвърлям всички",
            "Samo neobhodimite biskvitki",
            "Само необходимите бисквитки",
            "Prodalzhi bez priemane",
            "Продължи без приемане",
            "Atmesti",
            "Atmesti visus",
            "Tik butini slapukai",
            "Testi nepriimant",
            "Tęsti nepriimant",
            "Noraidit",
            "Noraidīt",
            "Noraidit visu",
            "Noraidīt visu",
            "Tikai nepieciesamas sikdatnes",
            "Tikai nepieciešamās sīkdatnes",
            "Turpinat bez piekrisanas",
            "Turpināt bez piekrišanas",
            "Keeldu",
            "Keeldu koigest",
            "Keeldu kõigest",
            "Ainult vajalikud kupsised",
            "Ainult vajalikud küpsised",
            "Jatka noustumata",
            "Jätka nõustumata",
            "Hafna",
            "Hafna ollu",
            "Hafna öllu",
            "Adeins naudsynlegar vafrakokur",
            "Aðeins nauðsynlegar vafrakökur",
            "Halda afram an samthykkis",
            "Halda áfram án samþykkis",
            "Diultaigh",
            "Diúltaigh",
            "Diultaigh do chach",
            "Diúltaigh do chách",
            "Fianain riachtanacha amhain",
            "Fianáin riachtanacha amháin",
            "Irrifjuta",
            "Irrifjuta kollox",
            "Cookies essenzjali biss",
            "Kompli minghajr accettazzjoni",
            "Kompli mingħajr aċċettazzjoni",
            "Reddet",
            "Tumunu Reddet",
            "Tümünü Reddet",
            "Kabul etmeden devam et",
            "Sadece gerekli cerezlere izin ver",
            "Sadece gerekli çerezlere izin ver",
            "Yalnizca gerekli cerezler",
            "Yalnızca gerekli çerezler",
        ],
        "contains": [
            "reject all cookies",
            "reject optional cookies",
            "reject non-essential cookies",
            "accept only necessary cookies",
            "accept only essential cookies",
            "only necessary cookies",
            "only essential cookies",
            "necessary cookies only",
            "essential cookies only",
            "continue without accepting",
            "cookies essentiels uniquement",
            "only noodzakelijke cookies",
            "solo cookies necesarias",
            "solo cookie necessari",
            "apenas cookies necessarios",
            "tylko niezbedne pliki cookie",
            "mono aparaitita cookies",
            "endast nodvandiga cookies",
            "kun nodvendige cookies",
            "bare nodvendige cookies",
            "vain valttamattomat evasteet",
            "csak a szukseges sütik",
            "samo nujni piskotki",
            "samo nuzni kolacici",
            "samo neobhodimite biskvitki",
            "tik butini slapukai",
            "ainult vajalikud kupsised",
            "cookies essenzjali biss",
            "gerekli cerezler",
            "gerekli çerezler",
        ],
    },
    "settings": {
        "exact": [
            "Settings",
            "Preferences",
            "Cookie Settings",
            "Cookie Preferences",
            "Privacy Settings",
            "Privacy Choices",
            "View Options",
            "View Cookie Options",
            "View Preferences",
            "More Options",
            "Manage Preferences",
            "Manage Privacy Preferences",
            "Manage Privacy Choices",
            "Customize Choices",
            "Customise Choices",
            "Einstellungen",
            "Cookie-Einstellungen",
            "Datenschutzeinstellungen",
            "Datenschutzoptionen",
            "Parameteres",
            "Parametres",
            "Paramètres",
            "Parametres de cookies",
            "Paramètres des cookies",
            "Gerer les preferences",
            "Gérer les préférences",
            "Voir les options",
            "Instellingen",
            "Cookie-instellingen",
            "Privacyvoorkeuren",
            "Voorkeuren beheren",
            "Opties bekijken",
            "Configurar",
            "Configuracion de cookies",
            "Configuración de cookies",
            "Preferencias de privacidad",
            "Gestionar preferencias",
            "Ver opciones",
            "Impostazioni",
            "Preferenze",
            "Impostazioni cookie",
            "Preferenze cookie",
            "Gestisci preferenze",
            "Visualizza opzioni",
            "Definicoes",
            "Definições",
            "Configuracoes",
            "Configurações",
            "Configuracoes de cookies",
            "Configurações de cookies",
            "Preferencias de privacidade",
            "Preferências de privacidade",
            "Gerir preferencias",
            "Gerir preferências",
            "Ver opcoes",
            "Ver opções",
            "Ustawienia",
            "Preferencje",
            "Ustawienia cookies",
            "Ustawienia plikow cookie",
            "Ustawienia plików cookie",
            "Zarzadzaj preferencjami",
            "Zarządzaj preferencjami",
            "Zobacz opcje",
            "Setari",
            "Setări",
            "Preferinte",
            "Preferințe",
            "Setari cookie",
            "Setări cookie",
            "Gestioneaza preferintele",
            "Gestionează preferințele",
            "Vezi optiunile",
            "Vezi opțiunile",
            "Nastaveni",
            "Nastavení",
            "Predvolby",
            "Nastaveni cookies",
            "Nastavení cookies",
            "Spravovat preference",
            "Zobrazit moznosti",
            "Zobrazit možnosti",
            "Installningar",
            "Inställningar",
            "Cookie-installningar",
            "Cookie-inställningar",
            "Hantera preferenser",
            "Visa alternativ",
            "Indstillinger",
            "Cookieindstillinger",
            "Administrer praeferencer",
            "Administrer præferencer",
            "Vis muligheder",
            "Innstillinger",
            "Cookieinnstillinger",
            "Administrer preferanser",
            "Vis alternativer",
            "Asetukset",
            "Evasteasetukset",
            "Evästeasetukset",
            "Hallitse asetuksia",
            "Nayta vaihtoehdot",
            "Näytä vaihtoehdot",
            "Rythmiseis",
            "Ρυθμίσεις",
            "Protimiseis",
            "Προτιμήσεις",
            "Rythmiseis cookies",
            "Ρυθμίσεις cookies",
            "Diacheirisi protimiseon",
            "Διαχείριση προτιμήσεων",
            "Provoli epilogon",
            "Προβολή επιλογών",
            "Beallitasok",
            "Beállítások",
            "Cookie-beallitasok",
            "Cookie-beállítások",
            "Beallitasok kezelese",
            "Beállítások kezelése",
            "Opciok megtekintese",
            "Opciók megtekintése",
            "Nastavenia",
            "Nastavenia cookies",
            "Spravovat preferencie",
            "Spravovať preferencie",
            "Zobrazit moznosti",
            "Zobraziť možnosti",
            "Nastavitve",
            "Nastavitve piskotkov",
            "Nastavitve piškotkov",
            "Upravljaj nastavitve",
            "Prikazi moznosti",
            "Prikaži možnosti",
            "Postavke",
            "Postavke kolacica",
            "Postavke kolačića",
            "Upravljaj postavkama",
            "Prikazi opcije",
            "Prikaži opcije",
            "Nastroyki",
            "Настройки",
            "Predpochtania",
            "Предпочитания",
            "Nastroyki za biskvitki",
            "Настройки за бисквитки",
            "Upravlenie na predpochtaniyata",
            "Управление на предпочитанията",
            "Vizh optsii",
            "Виж опциите",
            "Nustatymai",
            "Slapuku nustatymai",
            "Slapukų nustatymai",
            "Tvarkyti nuostatas",
            "Perziureti parinktis",
            "Peržiūrėti parinktis",
            "Iestatijumi",
            "Iestatījumi",
            "Sikdatnu iestatijumi",
            "Sīkdatņu iestatījumi",
            "Parvaldit preferences",
            "Pārvaldīt preferences",
            "Skatit iespejas",
            "Skatīt iespējas",
            "Seaded",
            "Kupsiste seaded",
            "Küpsiste seaded",
            "Halda eelistusi",
            "Vaata valikuid",
            "Stillingar",
            "Kokustillingar",
            "Kökustillingar",
            "Stjorna stillingum",
            "Stjórna stillingum",
            "Skoda valkosti",
            "Skoða valkosti",
            "Socruithe",
            "Sainroghanna",
            "Socruithe fianan",
            "Socruithe fianán",
            "Issettjar",
            "Isettjar",
            "Preferenzi",
            "Isettjar tal-cookies",
            "Ara l-ghazliet",
            "Ara l-għażliet",
            "Ayarlar",
            "Cerez ayarlari",
            "Çerez ayarları",
            "Cerez tercihleri",
            "Çerez tercihleri",
            "Gizlilik tercihleri",
            "Izin secenekleri",
            "İzin seçenekleri",
            "Secenekleri yonetin",
            "Seçenekleri yönetin",
            "Tercihleri yonetin",
            "Tercihleri yönetin",
        ],
        "contains": [
            "cookie settings",
            "cookie preferences",
            "privacy settings",
            "privacy choices",
            "view options",
            "view preferences",
            "more options",
            "manage preferences",
            "manage privacy preferences",
            "manage privacy choices",
            "customize choices",
            "customise choices",
            "cookie-instellingen",
            "preferencias de privacidad",
            "configuracoes de cookies",
            "configurações de cookies",
            "zarzadzaj preferencjami",
            "zarządzaj preferencjami",
            "vezi optiunile",
            "vezi opțiunile",
            "hantera preferenser",
            "vis muligheder",
            "vis alternativer",
            "hallitse asetuksia",
            "provoli epilogon",
            "προβολή επιλογών",
            "beallitasok kezelese",
            "beállítások kezelése",
            "spravovat preferencie",
            "spravovať preferencie",
            "upravljaj nastavitve",
            "upravljaj postavkama",
            "upravlenie na predpochtaniyata",
            "управление на предпочитанията",
            "tvarkyti nuostatas",
            "parvaldit preferences",
            "pārvaldīt preferences",
            "halda eelistusi",
            "stjorna stillingum",
            "stjórna stillingum",
            "ara l-ghazliet",
            "ara l-għażliet",
            "cerez ayarlari",
            "çerez ayarları",
            "seçenekleri yönetin",
            "secenekleri yonetin",
            "tercihleri yonetin",
            "tercihleri yönetin",
        ],
    },
    "dismiss": {
        "exact": [
            "OK",
            "Okay",
            "Continue",
            "Got it",
            "I Understand",
            "Understood",
            "Close",
            "Dismiss",
            "Later",
            "Not now",
            "Remind me later",
            "Weiter",
            "Verstanden",
            "Schliessen",
            "Schließen",
            "Continuer",
            "Compris",
            "J'ai compris",
            "Fermer",
            "Doorgaan",
            "Begrepen",
            "Sluiten",
            "Continuar",
            "Entendido",
            "Cerrar",
            "Mas tarde",
            "Más tarde",
            "Ahora no",
            "Continua",
            "Ho capito",
            "Chiudi",
            "Piu tardi",
            "Più tardi",
            "Non ora",
            "Compreendi",
            "Fechar",
            "Mais tarde",
            "Agora nao",
            "Agora não",
            "Kontynuuj",
            "Rozumiem",
            "Zamknij",
            "Pozniej",
            "Później",
            "Nie teraz",
            "Continua",
            "Continuă",
            "Am inteles",
            "Am înțeles",
            "Inchide",
            "Închide",
            "Mai tarziu",
            "Mai târziu",
            "Nu acum",
            "Pokracovat",
            "Pokračovat",
            "Rozumim",
            "Rozumím",
            "Zavrit",
            "Zavřít",
            "Pozdeji",
            "Později",
            "Ted ne",
            "Teď ne",
            "Fortsatt",
            "Fortsätt",
            "Jag forstar",
            "Jag förstår",
            "Stang",
            "Stäng",
            "Senare",
            "Inte nu",
            "Fortsaet",
            "Fortsæt",
            "Forstaet",
            "Forstået",
            "Luk",
            "Ikke nu",
            "Fortsett",
            "Skjonner",
            "Skjønner",
            "Lukk",
            "Senere",
            "Jatka",
            "Ymmarsin",
            "Ymmärsin",
            "Sulje",
            "Myohemmin",
            "Myöhemmin",
            "Ei nyt",
            "Synecheia",
            "Συνέχεια",
            "Katalava",
            "Κατάλαβα",
            "Kleisimo",
            "Κλείσιμο",
            "Argotera",
            "Αργότερα",
            "Ochi tora",
            "Όχι τώρα",
            "Folytatas",
            "Folytatás",
            "Ertettem",
            "Értettem",
            "Bezaras",
            "Bezárás",
            "Kesobb",
            "Később",
            "Pokracovat",
            "Pokračovať",
            "Rozumiem",
            "Zavriet",
            "Zavrieť",
            "Neskor",
            "Neskôr",
            "Teraz nie",
            "Nadaljuj",
            "Razumem",
            "Zapri",
            "Pozneje",
            "Ne zdaj",
            "Nastavi",
            "Razumijem",
            "Zatvori",
            "Kasnije",
            "Ne sada",
            "Prodalzhi",
            "Продължи",
            "Razbrah",
            "Разбрах",
            "Zatvori",
            "Затвори",
            "Po-kasno",
            "По-късно",
            "Ne sega",
            "Не сега",
            "Testi",
            "Tęsti",
            "Supratau",
            "Uzdaryti",
            "Veliau",
            "Vėliau",
            "Ne dabar",
            "Turpinat",
            "Turpināt",
            "Sapratu",
            "Aizvert",
            "Aizvērt",
            "Velak",
            "Vēlāk",
            "Mitte praegu",
            "Hiljem",
            "Sain aru",
            "Sulge",
            "Halda afram",
            "Halda áfram",
            "Skilid",
            "Skilið",
            "Loka",
            "Sidar",
            "Síðar",
            "Ekki nuna",
            "Ekki núna",
            "Lean ar aghaidh",
            "Thuig me",
            "Thuig mé",
            "Dun",
            "Dún",
            "Nios deanaí",
            "Níos déanaí",
            "Níl anois",
            "Kompli",
            "Fhimt",
            "Fhimt",
            "Aghlaq",
            "Agħlaq",
            "Aktar tard",
            "Mhux issa",
            "Devam et",
            "Anladim",
            "Anladım",
            "Kapat",
            "Daha sonra",
            "Simdi degil",
            "Şimdi değil",
            "Simdi değil",
        ],
        "contains": [],
    },
}


def flatten_action_vocabulary(action: str) -> list[str]:
    buckets = CONSENT_ACTION_VOCABULARY[action]
    return _dedupe_preserve_order([*buckets["exact"], *buckets["contains"]])


CONSENT_BUTTON_KEYWORDS: dict[str, list[str]] = {
    "accept": flatten_action_vocabulary("accept"),
    "reject": flatten_action_vocabulary("reject"),
}

SETTINGS_KEYWORDS: list[str] = flatten_action_vocabulary("settings")
DISMISS_BUTTON_KEYWORDS: list[str] = flatten_action_vocabulary("dismiss")

NECESSARY_KEYWORDS = [
    "necessary",
    "essential",
    "required",
    "strictly necessary",
    "erforderlich",
    "notwendig",
    "unbedingt erforderlich",
    "necessaire",
    "nécessaire",
    "strictement necessaire",
    "strictement nécessaire",
    "noodzakelijk",
    "strikt noodzakelijk",
    "necesario",
    "estrictamente necesario",
    "necessario",
    "strettamente necessario",
    "necessarios",
    "necessários",
    "essenciais",
    "niezbedne",
    "niezbędne",
    "konieczne",
    "esentiale",
    "esențiale",
    "nezbytne",
    "nezbytné",
    "nodvandiga",
    "nödvändiga",
    "nodvendige",
    "nødvendige",
    "valttamattomat",
    "välttämättömät",
    "aparaitita",
    "απαραίτητα",
    "szukseges",
    "szükséges",
    "nevyhnutne",
    "nevyhnutné",
    "nujni",
    "nuzni",
    "необходимите",
    "butini",
    "nepieciesamas",
    "nepieciešamās",
    "vajalikud",
    "naudsynlegar",
    "nauðsynlegar",
    "riachtanacha",
    "essenzjali",
    "gerekli",
    "zorunlu",
]

BANNER_SELECTORS = [
    "#cookie-banner",
    "#cookie-consent",
    "#consent-banner",
    "#cookieConsent",
    "#onetrust-banner-sdk",
    "#CybotCookiebotDialog",
    "#qc-cmp2-container",
    ".cookie-banner",
    ".cookie-consent",
    ".consent-banner",
    ".cookie-notice",
    "[class*='cookie-banner']",
    "[class*='cookie-consent']",
    "[class*='consent-banner']",
    "[id*='cookie']",
    "[id*='consent']",
    "[id*='gdpr']",
    "[id*='privacy']",
    "[class*='cookie']",
    "[class*='consent']",
    "[class*='gdpr']",
    "[role='dialog'][aria-label*='cookie' i]",
    "[role='dialog'][aria-label*='consent' i]",
    "div[data-testid*='cookie']",
    "div[data-testid*='consent']",
]

BANNER_TEXT_KEYWORDS = [
    "cookie",
    "cookies",
    "consent",
    "gdpr",
    "data protection",
    "datenschutz",
    "cerez",
    "çerez",
    "gizlilik",
    "slapuk",
    "sikdat",
    "sīkdat",
    "kupsis",
    "küpsis",
    "koku",
    "vafrakaka",
    "fianan",
    "fianán",
    "cookie-uri",
    "piškot",
    "kolac",
    "kolači",
    "бисквит",
]

BANNER_TEXT_PHRASES = [
    "privacy choices",
    "your privacy choices",
    "privacy preferences",
    "manage privacy preferences",
    "manage privacy choices",
    "we value your privacy",
    "cookie choices",
    "cookie preferences",
    "cookie settings",
    "cerez tercihleri",
    "çerez tercihleri",
    "gizlilik tercihleri",
    "nastaveni cookies",
    "nastavení cookies",
    "cookie-instellingen",
    "configuracion de cookies",
    "configuración de cookies",
    "impostazioni cookie",
    "configuracoes de cookies",
    "configurações de cookies",
]

BANNER_ATTR_HINTS = [
    "cookie",
    "consent",
    "gdpr",
    "cmp",
    "tcf",
    "onetrust",
    "didomi",
    "trustarc",
    "cookiebot",
    "sourcepoint",
    "privacy-mgmt",
    "sp_message",
    "sp_choice_type",
]

CMP_SIGNATURES: dict[str, list[str]] = {
    "OneTrust": ["onetrust", "optanon", "cookie-consent-banner"],
    "Cookiebot": ["cookiebot", "CookieConsent", "Cybot"],
    "Quantcast": ["quantcast", "__cmpLocator", "cmp2.js"],
    "TrustArc": ["trustarc", "truste", "consent-manager"],
    "Didomi": ["didomi"],
    "Usercentrics": ["usercentrics"],
    "Sourcepoint": ["sourcepoint", "privacy-mgmt", "sp_message", "sp_choice_type"],
}

COMPLIANCE_WEIGHTS: dict[str, float] = {
    "no_pre_consent_trackers": 0.25,
    "reject_option_available": 0.20,
    "equal_accept_reject_effort": 0.15,
    "no_dark_patterns": 0.15,
    "post_reject_compliance": 0.15,
    "transparent_information": 0.10,
}

STATE_OUTCOME_WEIGHTS: dict[str, float] = {
    "low_tracker_load": 0.45,
    "low_third_party_load": 0.25,
    "low_total_cookie_load": 0.15,
    "claimed_action_honesty": 0.15,
}

GRADE_THRESHOLDS = [
    (90, "A"),
    (75, "B"),
    (60, "C"),
    (40, "D"),
    (0, "F"),
]

PRIVACY_LINK_KEYWORDS = [
    "privacy policy",
    "privacy notice",
    "data protection",
    "datenschutz",
    "datenschutzerklaerung",
    "datenschutzerklärung",
    "politique de confidentialite",
    "politique de confidentialité",
    "privacybeleid",
    "privacyverklaring",
    "politica de privacidad",
    "política de privacidad",
    "informativa sulla privacy",
    "gizlilik politikasi",
    "gizlilik politikası",
    "politica de privacidade",
    "polityka prywatnosci",
    "polityka prywatności",
    "setari de confidentialitate",
    "nastaveni ochrany soukromi",
    "nastavení ochrany soukromí",
]

PURPOSE_KEYWORDS = [
    "analytics",
    "advertising",
    "personalization",
    "marketing",
    "functional",
    "preferences",
    "statistics",
    "targeting",
    "analyse",
    "werbung",
    "personalisierung",
    "analytique",
    "publicite",
    "publicité",
    "personnalisation",
    "analitica",
    "analítica",
    "personalizacao",
    "personalização",
    "statistiques",
    "estatisticas",
    "estatísticas",
]

VENDOR_KEYWORDS = [
    "google",
    "facebook",
    "meta",
    "analytics",
    "advertisement",
]

GUILT_TRIP_PHRASES = [
    "keep the site free",
    "support our journalist",
    "help us improve",
    "you'll miss out",
    "you will miss out",
    "miss personalized",
    "enjoy a better experience",
    "support free journalism",
    "we need your support",
    "without your support",
    "fund our work",
    "keep this site running",
    "best experience",
    "optimal experience",
    "unterstutzen sie uns",
    "unterstützen sie uns",
    "helfen sie uns",
    "kostenlos halten",
    "bessere erfahrung",
    "optimale erfahrung",
    "soutenez-nous",
    "aidez-nous",
    "meilleure experience",
    "meilleure expérience",
    "garder le site gratuit",
    "experience optimale",
    "expérience optimale",
    "steun ons",
    "help ons",
    "beste ervaring",
]

DOUBLE_NEGATIVE_PATTERN_SPECS = [
    {"pattern": r"don'?t\s+(not|reject|refuse|decline)", "flags": "i"},
    {"pattern": r"nicht\s+(ablehnen|verweigern)", "flags": "i"},
    {"pattern": r"ne\s+pas\s+(refuser|rejeter)", "flags": "i"},
    {"pattern": r"I\s+do\s+not\s+want\s+to\s+not", "flags": "i"},
]

FALLBACK_TRACKERS: dict[str, dict[str, str]] = {
    "doubleclick.net": {"vendor": "Google", "category": "Advertising"},
    "googlesyndication.com": {"vendor": "Google", "category": "Advertising"},
    "googleadservices.com": {"vendor": "Google", "category": "Advertising"},
    "googleads.g.doubleclick.net": {"vendor": "Google", "category": "Advertising"},
    "adnxs.com": {"vendor": "Xandr/Microsoft", "category": "Advertising"},
    "criteo.com": {"vendor": "Criteo", "category": "Advertising"},
    "criteo.net": {"vendor": "Criteo", "category": "Advertising"},
    "amazon-adsystem.com": {"vendor": "Amazon", "category": "Advertising"},
    "adsrvr.org": {"vendor": "The Trade Desk", "category": "Advertising"},
    "rubiconproject.com": {"vendor": "Rubicon Project", "category": "Advertising"},
    "pubmatic.com": {"vendor": "PubMatic", "category": "Advertising"},
    "casalemedia.com": {"vendor": "Casale Media", "category": "Advertising"},
    "openx.net": {"vendor": "OpenX", "category": "Advertising"},
    "taboola.com": {"vendor": "Taboola", "category": "Advertising"},
    "outbrain.com": {"vendor": "Outbrain", "category": "Advertising"},
    "google-analytics.com": {"vendor": "Google", "category": "Analytics"},
    "googletagmanager.com": {"vendor": "Google", "category": "Analytics"},
    "hotjar.com": {"vendor": "Hotjar", "category": "Analytics"},
    "hotjar.io": {"vendor": "Hotjar", "category": "Analytics"},
    "mouseflow.com": {"vendor": "Mouseflow", "category": "Analytics"},
    "newrelic.com": {"vendor": "New Relic", "category": "Analytics"},
    "segment.io": {"vendor": "Segment", "category": "Analytics"},
    "segment.com": {"vendor": "Segment", "category": "Analytics"},
    "amplitude.com": {"vendor": "Amplitude", "category": "Analytics"},
    "mixpanel.com": {"vendor": "Mixpanel", "category": "Analytics"},
    "clarity.ms": {"vendor": "Microsoft", "category": "Analytics"},
    "scorecardresearch.com": {"vendor": "comScore", "category": "Analytics"},
    "chartbeat.com": {"vendor": "Chartbeat", "category": "Analytics"},
    "chartbeat.net": {"vendor": "Chartbeat", "category": "Analytics"},
    "facebook.net": {"vendor": "Meta", "category": "Social"},
    "facebook.com": {"vendor": "Meta", "category": "Social"},
    "fbcdn.net": {"vendor": "Meta", "category": "Social"},
    "connect.facebook.net": {"vendor": "Meta", "category": "Social"},
    "twitter.com": {"vendor": "X/Twitter", "category": "Social"},
    "platform.twitter.com": {"vendor": "X/Twitter", "category": "Social"},
    "linkedin.com": {"vendor": "LinkedIn", "category": "Social"},
    "snap.licdn.com": {"vendor": "LinkedIn", "category": "Social"},
    "tiktok.com": {"vendor": "TikTok", "category": "Social"},
    "demdex.net": {"vendor": "Adobe", "category": "Fingerprinting"},
    "omtrdc.net": {"vendor": "Adobe", "category": "Fingerprinting"},
    "krxd.net": {"vendor": "Salesforce/Krux", "category": "Fingerprinting"},
    "bluekai.com": {"vendor": "Oracle", "category": "Fingerprinting"},
    "exelator.com": {"vendor": "Nielsen", "category": "Fingerprinting"},
    "quantserve.com": {"vendor": "Quantcast", "category": "Fingerprinting"},
}

COOKIE_HEURISTIC_SPECS = [
    {"pattern": r"^_ga$|^_ga_", "flags": "i", "vendor": "Google", "category": "Analytics"},
    {"pattern": r"^_gid$", "flags": "i", "vendor": "Google", "category": "Analytics"},
    {"pattern": r"^_gat", "flags": "i", "vendor": "Google", "category": "Analytics"},
    {"pattern": r"^__utm", "flags": "i", "vendor": "Google", "category": "Analytics"},
    {"pattern": r"_fbp|_fbc|fbp", "flags": "i", "vendor": "Meta", "category": "Social"},
    {"pattern": r"^_hjid|^_hj", "flags": "i", "vendor": "Hotjar", "category": "Analytics"},
    {"pattern": r"^_tt_", "flags": "i", "vendor": "TikTok", "category": "Social"},
    {"pattern": r"^li_|^bcookie|^lidc", "flags": "i", "vendor": "LinkedIn", "category": "Social"},
    {"pattern": r"^IDE$|^test_cookie$|^DSID$", "flags": "i", "vendor": "Google", "category": "Advertising"},
    {
        "pattern": r"^NID$|^APISID$|^SAPISID$|^SID$|^SSID$|^HSID$",
        "flags": "i",
        "vendor": "Google",
        "category": "Functional",
    },
    {"pattern": r"^_pin_|^_pinterest_", "flags": "i", "vendor": "Pinterest", "category": "Social"},
    {"pattern": r"^amp_", "flags": "i", "vendor": "Amplitude", "category": "Analytics"},
    {"pattern": r"^mp_", "flags": "i", "vendor": "Mixpanel", "category": "Analytics"},
]


def _regex_flags(flags: str) -> int:
    value = 0
    if "i" in flags:
        value |= re.I
    if "m" in flags:
        value |= re.M
    if "s" in flags:
        value |= re.S
    return value


def compile_cookie_heuristics() -> list[tuple[re.Pattern[str], str, str]]:
    return [
        (re.compile(spec["pattern"], _regex_flags(spec["flags"])), spec["vendor"], spec["category"])
        for spec in COOKIE_HEURISTIC_SPECS
    ]


def compile_double_negative_patterns() -> list[re.Pattern[str]]:
    return [
        re.compile(spec["pattern"], _regex_flags(spec["flags"]))
        for spec in DOUBLE_NEGATIVE_PATTERN_SPECS
    ]


def _matches_action(normalized: str, action: str) -> bool:
    exact = [normalize_match_text(item) for item in CONSENT_ACTION_VOCABULARY[action]["exact"]]
    contains = [normalize_match_text(item) for item in CONSENT_ACTION_VOCABULARY[action]["contains"]]

    if normalized in exact:
        return True

    return any(term and term in normalized for term in contains)


def classify_consent_action(text: str | None) -> str:
    normalized = normalize_match_text(text)
    if not normalized:
        return "unknown"

    for action in ("reject", "accept", "settings", "dismiss"):
        if _matches_action(normalized, action):
            return action

    return "unknown"


def build_extension_shared_payload() -> dict[str, object]:
    return {
        "fallbackTrackers": FALLBACK_TRACKERS,
        "cookieHeuristics": COOKIE_HEURISTIC_SPECS,
        "cmpSignatures": CMP_SIGNATURES,
        "consentVocabulary": CONSENT_ACTION_VOCABULARY,
        "consentButtonKeywords": CONSENT_BUTTON_KEYWORDS,
        "settingsKeywords": SETTINGS_KEYWORDS,
        "dismissButtonKeywords": DISMISS_BUTTON_KEYWORDS,
        "necessaryKeywords": NECESSARY_KEYWORDS,
        "bannerSelectors": BANNER_SELECTORS,
        "bannerTextKeywords": BANNER_TEXT_KEYWORDS,
        "bannerTextPhrases": BANNER_TEXT_PHRASES,
        "bannerAttrHints": BANNER_ATTR_HINTS,
        "complianceWeights": COMPLIANCE_WEIGHTS,
        "stateOutcomeWeights": STATE_OUTCOME_WEIGHTS,
        "grades": [{"threshold": threshold, "grade": grade} for threshold, grade in GRADE_THRESHOLDS],
        "privacyLinkKeywords": PRIVACY_LINK_KEYWORDS,
        "purposeKeywords": PURPOSE_KEYWORDS,
        "vendorKeywords": VENDOR_KEYWORDS,
        "guiltTripPhrases": GUILT_TRIP_PHRASES,
        "doubleNegativePatterns": DOUBLE_NEGATIVE_PATTERN_SPECS,
    }
