from __future__ import annotations


CONSENT_ACTION_CASES: list[tuple[str, str, str]] = [
    ("English accept continue", "Accept and continue", "accept"),
    ("English reject optional", "Reject Optional Cookies", "reject"),
    ("English reject essential", "Essential cookies only", "reject"),
    ("English reject necessary", "Necessary cookies only", "reject"),
    ("English reject continue", "Continue without accepting", "reject"),
    ("English settings", "Manage Preferences", "settings"),
    ("English dismiss", "Not now", "dismiss"),
    ("German", "Einstellungen", "settings"),
    ("French", "Continuer sans accepter", "reject"),
    ("Dutch", "Cookie-instellingen", "settings"),
    ("Spanish", "Aceptar todo", "accept"),
    ("Italian", "Solo cookie necessari", "reject"),
    ("Portuguese", "Gerir preferências", "settings"),
    ("Polish", "Tylko niezbędne pliki cookie", "reject"),
    ("Romanian", "Acceptă", "accept"),
    ("Czech", "Nastavení cookies", "settings"),
    ("Swedish", "Endast nödvändiga cookies", "reject"),
    ("Danish", "Vis muligheder", "settings"),
    ("Norwegian", "Godta alle", "accept"),
    ("Finnish", "Vain välttämättömät evästeet", "reject"),
    ("Greek", "Προβολή επιλογών", "settings"),
    ("Hungarian", "Beállítások kezelése", "settings"),
    ("Slovak", "Prijať všetko", "accept"),
    ("Slovenian", "Nastavitve piškotkov", "settings"),
    ("Croatian", "Prihvati sve", "accept"),
    ("Bulgarian", "Само необходимите бисквитки", "reject"),
    ("Lithuanian", "Slapukų nustatymai", "settings"),
    ("Latvian", "Pārvaldīt preferences", "settings"),
    ("Estonian", "Nõustun", "accept"),
    ("Icelandic", "Halda áfram án samþykkis", "reject"),
    ("Irish", "Lean ar aghaidh", "dismiss"),
    ("Maltese", "Aċċetta kollox", "accept"),
    ("Turkish", "Çerez ayarları", "settings"),
]
