"""Build the lightweight AECCS extension study snapshot from real_combined."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "data" / "real_combined" / "processed"
DEFAULT_OUTPUT = ROOT / "extension" / "lib" / "study-snapshot.js"

PET_NAME_MAP = {
    "brave_shields": "Brave Shields",
    "privacy_badger": "Privacy Badger",
    "ublock_origin": "uBlock Origin",
    "firefox_etp_strict": "Firefox ETP Strict",
    "consent_o_matic": "Consent-O-Matic",
    "firefox_etp_standard": "Firefox ETP Standard",
}


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _pct_to_ratio(value: float) -> float:
    return round(float(value) / 100.0, 4)


def build_snapshot(processed_dir: Path) -> dict:
    aggregate = _read_json(processed_dir / "aggregate_metrics.json")
    pets = _read_json(processed_dir / "pets_summary.json")
    manifest = _read_json(processed_dir / "run_manifest.json")

    metadata = {
        "label": "AECCS 1000-site combined study snapshot",
        "sourceMode": manifest["source_mode"],
        "runId": manifest["run_id"],
        "snapshotDate": "2026-03-06",
        "snapshotDateLabel": "March 6, 2026",
        "generatedAt": manifest["created_at"],
        "sampleSize": aggregate["summary"]["total_sites_crawled"],
        "successfulCrawls": aggregate["summary"]["successful_crawls"],
        "failedCrawls": aggregate["summary"]["failed_crawls"],
        "bannerSites": aggregate["summary"]["sites_with_banners"],
        "sitesWithoutBanners": aggregate["summary"]["sites_without_banners"],
        "avgCompliance": aggregate["compliance_scores"]["avg_score"],
        "missingRejectRate": _pct_to_ratio(aggregate["dark_patterns"]["by_type"]["missing_reject"]["percentage"]),
        "multiLayerRate": _pct_to_ratio(aggregate["dark_patterns"]["by_type"]["multi_layer_rejection"]["percentage"]),
        "rejectReducesTrackersRate": _pct_to_ratio(
            aggregate["tracker_analysis"]["before_vs_after_consent"]["reject_reduces_trackers_percentage"]
        ),
        "rejectEliminatesTrackersRate": _pct_to_ratio(
            aggregate["tracker_analysis"]["before_vs_after_consent"]["reject_eliminates_all_trackers_percentage"]
        ),
        "publicSector": {
            "successfulSites": aggregate["pre_consent_violations"]["by_category"]["government"]["total"],
            "avgCompliance": aggregate["compliance_scores"]["by_category"]["government"]["avg_score"],
            "preConsentTrackerRate": _pct_to_ratio(
                aggregate["pre_consent_violations"]["by_category"]["government"]["percentage"]
            ),
        },
    }

    pet_study_results = []
    for item in pets["browser_pets_ranking"]:
        pet_study_results.append(
            {
                "name": PET_NAME_MAP[item["pet_name"]],
                "type": "browser" if "firefox" in item["pet_name"] or "brave" in item["pet_name"] else "extension",
                "studyRank": item["rank"],
                "sitesTested": item["sites_tested"],
                "trackerReductionPct": item["avg_tracker_reduction_pct"],
                "requestReductionPct": item["avg_request_reduction_pct"],
                "studyLabel": f"{item['avg_tracker_reduction_pct']:+.1f}% avg tracker reduction in study",
            }
        )

    raw_cmp_rows = []
    with (processed_dir / "cmp_comparison.csv").open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            if row["cmp_name"] == "No CMP Detected":
                continue
            raw_cmp_rows.append(row)

    cmp_study_results = []
    for index, row in enumerate(raw_cmp_rows, start=1):
        cmp_study_results.append(
            {
                "name": row["cmp_name"],
                "sampleSize": int(row["site_count"]),
                "avgScore": float(row["avg_compliance_score"]),
                "rejectRate": _pct_to_ratio(float(row["pct_with_reject_button"])),
                "petScore": float(row["pet_score"]),
                "studyRank": index,
            }
        )

    return {
        "metadata": metadata,
        "petStudyResults": pet_study_results,
        "cmpStudyResults": cmp_study_results,
    }


def emit_js(snapshot: dict) -> str:
    payload = json.dumps(snapshot, indent=2, ensure_ascii=True)
    return (
        "/* Generated by scripts/build_extension_study_snapshot.py from data/real_combined/processed. */\n"
        "(function () {\n"
        '  "use strict";\n\n'
        f"  const snapshot = {payload};\n\n"
        '  if (typeof globalThis !== "undefined") {\n'
        "    globalThis.AECCSStudySnapshot = snapshot;\n"
        "  }\n"
        "})();\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    snapshot = build_snapshot(args.input_dir)
    args.output.write_text(emit_js(snapshot), encoding="utf-8")
    print(f"[OK] Wrote {args.output}")


if __name__ == "__main__":
    main()
