"""Build the generated AECCS extension shared-config asset from Python truth."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from shared_constants import build_extension_shared_payload


DEFAULT_OUTPUT = ROOT / "extension" / "lib" / "shared-config.js"


def build_payload() -> dict[str, object]:
    return build_extension_shared_payload()


def emit_js(payload: dict[str, object]) -> str:
    body = json.dumps(payload, indent=2, ensure_ascii=True)
    return (
        "/* Generated by scripts/build_extension_shared_config.py from Python shared constants. */\n"
        "(function () {\n"
        '  "use strict";\n\n'
        f"  const sharedConfig = {body};\n\n"
        '  if (typeof globalThis !== "undefined") {\n'
        "    globalThis.AECCSSharedConfig = sharedConfig;\n"
        "  }\n"
        "})();\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    payload = build_payload()
    args.output.write_text(emit_js(payload), encoding="utf-8")
    print(f"[OK] Wrote {args.output}")


if __name__ == "__main__":
    main()
